language: nix
matrix:
    include:
        - os: linux
          sudo: false
          script:
              - ./maintainers/scripts/travis-nox-review-pr.sh verify
              - ./maintainers/scripts/travis-nox-review-pr.sh check
              - ./maintainers/scripts/travis-nox-review-pr.sh tarball
        - os: linux
          sudo: required
          dist: trusty
          script: ./maintainers/scripts/travis-nox-review-pr.sh pr
        - os: osx
          osx_image: xcode7.3
          script: ./maintainers/scripts/travis-nox-review-pr.sh pr
git:
    depth: 1
env:
    global:
        - GITHUB_TOKEN=5edaaf1017f691ed34e7f80878f8f5fbd071603f
